version: 0.2
phases:
  pre_build:
    commands:
      # - terraform init
      # - terraform validate
  
  build:
    commands:
      - pwd
      - ls
      - cd sample-app-infra
      - terraform apply -input=false ${TF_VAR_FILE:-$STAGE}.tfplan