version: 0.2
phases:
  pre_build:
    commands:
      # - cd sample-app-infra
      # - terraform init
      # - terraform validate
  
  build:
    commands:
      - terraform apply -input=false ${TF_VAR_FILE:-$STAGE}.tfplan